### ISSUE TITLE
unable to install django-utils library

### ISSUE THREAD

**Issue by ankitjaadoo** [ericholscher/django-test-utils#46]
I am getting an error while installing django-test-utils package either using "pip install django-celery-utils==0.3" or simply "pip install django-celery-utils".

The error is as follows:

ERROR: Command errored out with exit status 1:
     command: 'c:\users\hp\django_version_update\aa1_portal_dev\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hp\\AppData\\Local\\Temp\\pip-install-nwmmzfa1\\beautifulsoup_9c63a36ebb8e4620ab876de8343c85f1\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hp\\AppData\\Local\\Temp\\pip-install-nwmmzfa1\\beautifulsoup_9c63a36ebb8e4620ab876de8343c85f1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Hp\AppData\Local\Temp\pip-pip-egg-info-nj3g4utk'
         cwd: C:\Users\Hp\AppData\Local\Temp\pip-install-nwmmzfa1\beautifulsoup_9c63a36ebb8e4620ab876de8343c85f1\ 
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hp\AppData\Local\Temp\pip-install-nwmmzfa1\beautifulsoup_9c63a36ebb8e4620ab876de8343c85f1\setup.py", line 3
        "You're trying to run a very old release of Beautiful Soup under Python 3. This will not work."<>"Please use Beautiful Soup 4, available through the pip package 'beautifulsoup4'."
                                                                                                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/f2/6c9f2f3e696ee6a1fb0e4d7850617e224ed2b0b1e872110abffeca2a09d4/BeautifulSoup-3.2.2.tar.gz#sha256=a04169602bff6e3138b1259dbbf491f5a27f9499dea9a8fbafd48843f9d89970 (from https://pypi.org/simple/beautifulsoup/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached BeautifulSoup-3.2.1.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hp\django_version_update\aa1_portal_dev\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hp\\AppData\\Local\\Temp\\pip-install-nwmmzfa1\\beautifulsoup_43f589a08acd4d9ca2147715b68dd32b\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hp\\AppData\\Local\\Temp\\pip-install-nwmmzfa1\\beautifulsoup_43f589a08acd4d9ca2147715b68dd32b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Hp\AppData\Local\Temp\pip-pip-egg-info-7snaygzq'
         cwd: C:\Users\Hp\AppData\Local\Temp\pip-install-nwmmzfa1\beautifulsoup_43f589a08acd4d9ca2147715b68dd32b\ 
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hp\AppData\Local\Temp\pip-install-nwmmzfa1\beautifulsoup_43f589a08acd4d9ca2147715b68dd32b\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz#sha256=6a8cb4401111e011b579c8c52a51cdab970041cc543814bbd9577a4529fe1cdb (from https://pypi.org/simple/beautifulsoup/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached BeautifulSoup-3.2.0.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hp\django_version_update\aa1_portal_dev\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hp\\AppData\\Local\\Temp\\pip-install-nwmmzfa1\\beautifulsoup_d731155f369645a4841989d0b00c9d47\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hp\\AppData\\Local\\Temp\\pip-install-nwmmzfa1\\beautifulsoup_d731155f369645a4841989d0b00c9d47\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Hp\AppData\Local\Temp\pip-pip-egg-info-_dl93jar'
         cwd: C:\Users\Hp\AppData\Local\Temp\pip-install-nwmmzfa1\beautifulsoup_d731155f369645a4841989d0b00c9d47\ 
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hp\AppData\Local\Temp\pip-install-nwmmzfa1\beautifulsoup_d731155f369645a4841989d0b00c9d47\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/33/fe/15326560884f20d792d3ffc7fe8f639aab88647c9d46509a240d9bfbb6b1/BeautifulSoup-3.2.0.tar.gz#sha256=0dc52d07516c1665c9dd9f0a390a7a054bfb7b147a50b2866fb116b8909dfd37 (from https://pypi.org/simple/beautifulsoup/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement BeautifulSoup (from django-test-utils)
ERROR: No matching distribution found for BeautifulSoup

Here is the list of libraries in my requirements.txt file:

amqp                  5.0.5  
anyjson               0.3.3  
asgiref               3.3.1  
attrs                 20.3.0 
aws-encryption-sdk    2.0.0  
awscli                1.19.3 
Babel                 2.9.0  
beautifulsoup4        4.9.3  
billiard              3.6.3.0
boto                  2.49.0 
boto3                 1.17.3
botocore              1.20.3
celery                5.0.5
cffi                  1.14.4
click                 7.1.2
click-didyoumean      0.0.3
click-plugins         1.1.1
click-repl            0.1.6
colorama              0.4.3
cryptography          3.4.1
Django                3.1.6
django-celery         3.1.17
django-ckeditor       6.0.0
django-js-asset       1.2.2
django-jsonfield      1.4.1
django-storages-redux 1.3.3
django-tagging        0.5.0
docutils              0.15.2
flower                0.9.3
humanize              3.2.0
importlib-metadata    3.4.0
jmespath              0.10.0
kombu                 5.0.2
Pillow                8.1.0
pip                   21.0.1
prometheus-client     0.8.0
prompt-toolkit        3.0.14
pyasn1                0.4.8
pycparser             2.20
python-dateutil       2.8.1
pytz                  2021.1
PyYAML                5.3.1
rsa                   4.5
s3transfer            0.3.4
semantic-version      2.8.5
setuptools            47.1.0
setuptools-rust       0.11.6
six                   1.15.0
soupsieve             2.1
sqlparse              0.4.1
toml                  0.10.2
tornado               5.1.1
typing-extensions     3.7.4.3
urllib3               1.26.3
vine                  5.0.0
wcwidth               0.2.5
wrapt                 1.12.1
zipp                  3.4.0

Kindly let me know what needs to be done here.

**Comment by albertyw** [comment]
It looks like `django-test-utils` only works on very outdated python 2.
